#!/bin/bash
set -e

path="$(rustc --print sysroot)/lib"

if ! command -v rustup >/dev/null 2>&1; then
    echo "Error: 'rustup' command is not installed or not in PATH."
fi

if [ -z "$DYLD_LIBRARY_PATH" ]; then
    export DYLD_LIBRARY_PATH="$path"
fi

./target/debug/intrust "$@"
