[package]
name = "repl_tools"
version = "0.1.0"
authors = ["Headcrab Contributors"]
edition = "2018"
repository = "https://github.com/headcrab-rs/headcrab/"
license = "MIT OR Apache-2.0"

[dependencies]
rustyline = "14.0.0"
